// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsRexsTqS8gqqschtszqPQwUiROnTGFJ0',
    appId: '1:106262507523:web:2e06f6704b5535737d5e36',
    messagingSenderId: '106262507523',
    projectId: 'spaidemo2',
    authDomain: 'spaidemo2.firebaseapp.com',
    databaseURL: 'https://spaidemo2-default-rtdb.firebaseio.com',
    storageBucket: 'spaidemo2.appspot.com',
    measurementId: 'G-YM7NHMSC72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZu1w30tHgegCNBNi7mB38Fphs6JHRRNQ',
    appId: '1:106262507523:android:5bd5b7a58fbec6d67d5e36',
    messagingSenderId: '106262507523',
    projectId: 'spaidemo2',
    databaseURL: 'https://spaidemo2-default-rtdb.firebaseio.com',
    storageBucket: 'spaidemo2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-wuw2PaC3RWwjjMmCHhqNoZvegKScgWA',
    appId: '1:106262507523:ios:890380c1bde5f3d97d5e36',
    messagingSenderId: '106262507523',
    projectId: 'spaidemo2',
    databaseURL: 'https://spaidemo2-default-rtdb.firebaseio.com',
    storageBucket: 'spaidemo2.appspot.com',
    iosClientId: '106262507523-fdso0htq4165d8b9ntn3om95cb3qlb0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.spaiDemo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-wuw2PaC3RWwjjMmCHhqNoZvegKScgWA',
    appId: '1:106262507523:ios:890380c1bde5f3d97d5e36',
    messagingSenderId: '106262507523',
    projectId: 'spaidemo2',
    databaseURL: 'https://spaidemo2-default-rtdb.firebaseio.com',
    storageBucket: 'spaidemo2.appspot.com',
    iosClientId: '106262507523-fdso0htq4165d8b9ntn3om95cb3qlb0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.spaiDemo1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsRexsTqS8gqqschtszqPQwUiROnTGFJ0',
    appId: '1:106262507523:web:b1eb49a1c7bf25b07d5e36',
    messagingSenderId: '106262507523',
    projectId: 'spaidemo2',
    authDomain: 'spaidemo2.firebaseapp.com',
    databaseURL: 'https://spaidemo2-default-rtdb.firebaseio.com',
    storageBucket: 'spaidemo2.appspot.com',
    measurementId: 'G-ZX8QPGHS59',
  );
}
